## LLM Hugging MODEL Repo id
MODEL_ID: gpt2-medium

EMBEDDING_TYPE : NORMAL #INSTRUCT

CHUNK_SIZE: 1000

CHUNK_OVERLAP : 50

# HUGGING FACE EMBEDDING MODEL
EMBEDDING_MODEL_NAME: "sentence-transformers/all-MiniLM-L6-v2"
